version: '3.4'

services:
  osr.web.api:
    image: ${DOCKER_REGISTRY}osrwebapi
    build:
      context: .
      dockerfile: OSR.Web.Api/Dockerfile
    depends_on:               # launch myapi service until the other services have started
      - sqldb
  
  sqldb:
    image: microsoft/mssql-server-linux:latest
    container_name: osr-mssql
    hostname: mssql
    ports:
      - 1403:1433
      #- 8011:1434
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=whatever@2