version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1.401-sdk
    steps:
      - checkout
      - run: dotnet build  ./DDD.OnlineSchoolRegistration.sln
  test:
    docker:
      - image: microsoft/dotnet:2.1.401-sdk
    steps:
      - checkout
      - run: dotnet test ./Tests/OSR.Domain.UnitTests
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test